Repository canonical/slurmrestd-operator, pull requests merged in 2023-01, with the labels that each got.

#1 Add initial CICD pipeline w/initial unit test
  .github/workflows/build-and-test.yaml
  .github/workflows/pull-request.yaml
  pyproject.toml
  tests/unit/test_charm.py
  tox.ini
Labels: Type: Enhancement

#2 Add inclusive naming check
  .github/workflows/build-and-test.yaml
Labels: Type: Enhancement

#4 enhance: Add templates for pull requests and issues
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/enhancement_proposal.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Type: Enhancement

#5 Initial Omnivector Feedback
  .github/ISSUE_TEMPLATE/bug_report.yml
  LICENSE
  pyproject.toml
Labels: Type: Enhancement

#7 Add integration tests for slurmrestd operator
  .github/workflows/build-and-test.yaml
  .github/workflows/ci.yaml
  .github/workflows/pull-request.yaml
  pyproject.toml
  src/charm.py
  src/interface_slurmrestd.py
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/test_charm.py
  tests/unit/test_charm.py
  tox.ini
Labels: Status: Testing Needed, Type: Enhancement

#9 Fix linting and spelling errors in source code
  .github/ISSUE_TEMPLATE/bug_report.yml
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/test_charm.py
Labels: Type: Cleanup, Type: Documentation
